accounts/urls.py
from django.urls import path
from . import views
app_name="accounts"

#회원가입 로그인 로그아웃
urlpatterns=[
    path('login/',views.login, name="login"),
    path('signup/',views.signup,name="signup"),
    ]

eunsta/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('posts/',include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name="posts"
urlpatterns=[
    path('',views.list,name="list"),
    path('new/',views.new,name="new"),
    path('<int:id>/like/',views.like,name="like"),
    ]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings 
# Create your models here.
class Post(models.Model):
    title = models.TextField()
    #1:N
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="likeposts",blank=True)    

    

posts/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title',]

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import login as auth_login
# Create your views here.
def login(request):
    # 로그인을 하기 위한 폼 =>create와 비슷 
    if request.method=="POST":
        login_form = AuthenticationForm(request,request.POST)
        if login_form.is_valid():
            # 유저정보 넣기
            auth_login(request,login_form.get_user())
            return redirect("accounts:login")
    else:
        login_form = AuthenticationForm()
    return render(request,"accounts/login.html",{"login_form":login_form})
    
def signup(request):
    if request.method=="POST":
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect("accounts:login")
        #검증에 통과하지 못한다면통과
    else:
        user_form = UserCreationForm()
    return render(request,"accounts/signup.html",{"user_form":user_form})
    

posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from .forms import PostForm
# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request,"posts/list.html",{"posts":posts})
    
def new(request):
    
    if request.method=="POST":
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            #유저정보 넣기
            post.user = request.user
            post.save()
            return redirect("posts:list")
    else:
        post_form = PostForm()
    return render(request,"posts/form.html",{"post_form":post_form})
    
def like(request,id):
    post = Post.objects.get(id=id)
    #유저의 정보 담기
    me = request.user
    #좋아요 이미 눌렀음 취소
    #
    # if me in post.likes.all(): #내가 있니
    #     pass
    # else:
    #     pass
    
    if post in me.likeposts.all():#post가 있니
        # post.likes.remove(me) #post에서 me삭제
        me.likeposts.remove(post) 
    else:
        # post.likes.add(me)
        me.likeposts.add(post) #좋아요
    return redirect("posts:list")

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>login페이지</h1>
    <form method="post">
        {% csrf_token %}
        {{login_form}}
        <input type="submit"/>
    </form>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{user_form}}
        <input type="submit"/>
    </form>
    
</body>
</html>

posts/templates/posts/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        로그인함
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{post_form}}
        <input type="submit"/>
    </form>
</body>
</html>

posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% for post in posts %}
        {{post.title}}
        {% if post in user.likeposts.all %}
            <a href="{% url "posts:like" post.id %}">좋아요취소</a>
        {% else %}
            <a href="{% url "posts:like" post.id %}">좋아요</a>
        {% endif %}
    {% endfor %}
</body>
</html>